### PR TITLE
Update CommandManager.java

### PR DESCRIPTION
**Pull request by TrivCodez**
I refactored the code by removing unnecessary variables and methods, simplifying it with Java 8 features like lambda expressions and method references, improving readability through reorganization and added whitespace, and enhancing clarity by removing redundant comments and introducing meaningful variable names.

### CODE REVIEW

**Comment by OsakiTsukiko** [comment]
why remove the license header comment

**Comment by TrivCodez** [comment]
Sorry about that, i'll re add that

**Comment by TrivCodez** [comment]
@OsakiTsukiko fixed

**Comment by TrivCodez** [comment]
i;ve fixed

**Comment by TrivCodez** [comment]
i've fixed*

**Comment by TrivCodez** [comment]
check new PR

**Comment by OsakiTsukiko** [comment]
there was no need to make new pr, you can push changes to this pr, maybe close the new one so its not confusing (#55).

**Comment by OsakiTsukiko** [comment]
also, you can edit a message :wink:

**Comment by coltonk9043** [comment]
Closing since new PR issued.

**Pull request closed without merging**
