### PR TITLE
Update CommandManager.java

### PR DESCRIPTION
**Pull request by TrivCodez**
new

### CODE REVIEW

**Comment by coltonk9043** [comment]
Hey! I'm not home rn so I'll review this once I'm back. I briefly looked over it and it looks great though.

**Comment by TrivCodez** [comment]
Alright, No problem!

**Comment by TrivCodez** [comment]
**improved code efficiency and readability by:

- Implementing try-with-resources statements for better resource handling
- Simplifying methods using StringBuilder for more concise string manipulation
- Leveraging Java 8's removeIf and anyMatch methods for more expressive and efficient collection operations
- Removing unnecessary comments and whitespace for easier code maintainability**

**Comment by coltonk9043** [comment]
Overall looked pretty good. I am a fan of the removeIf and anyMatch method changes. I have pushed a commit that fixes some issues I have/found:

While I do agree that the format of javadoc I used was a little excessive, I do believe that every public method should at least have a minimal amount of documentation to at least state what the method is doing, even if it is clear from the name of the method. I have added those back but made them single-line javadoc comments to save a little bit of space.

Another small issue was that all of the commands were gone. The constructor of 'CommandManager' uses reflection to find all of the fields that are declared as a sub-class of 'Command', and then adds them to the Map of commands. This way, all I have to do to add a command is declare it in 'CommandManager' for it to show up in-game.

Overall though, very good. Let me know what you think of the changes I made. If you are happy with it, I can likely merge this tomorrow. Thanks :)

**Review by coltonk9043 — APPROVED** [review]
Merging PR. Thanks again.

**Pull request merged**
